language: php

php:
    - 5.4
    - 5.5
    - 5.6

notifications:
    email: dev@anime-db.org

before_script:
    - composer self-update
    - composer global require "fxp/composer-asset-plugin:~1.0.0"
    - composer install --prefer-source --no-interaction

script:
    - phpunit --verbose --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
