module.exports = function(grunt) {
    grunt.file.defaultEncoding = 'UTF-8';

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        project: {
            dist: {
                js: 'src/Resources/public/js/dist/'
            },
            src: {
                node: 'node_modules/',
                js: 'src/Resources/public/js/src/',
                vendor: 'src/Resources/public/js/vendor/'
            }
        },
        concat: {
            js: {
                src: [
                    '<%= project.src.node %>jquery/dist/jquery.min.js',
                    '<%= project.src.node %>Hinclude/hinclude.js',
                    '<%= project.src.node %>jquery-form/jquery.form.js',
                    '<%= project.src.vendor %>*',
                    '<%= project.src.js %>form.js',
                    '<%= project.src.js %>lib.js',
                    '<%= project.src.js %>main.js'
                ],
                dest: '<%= project.dist.js %>main.js'
            }
        },
        uglify: {
            options: {
                banner: '/* This file is auto-generated by grant at <%= grunt.template.today("yyyy-mm-dd") %> */\n',
                compress: {
                    drop_console: true
                }
            },
            build: {
                files: {
                    '<%= project.dist.js %>main.min.js': '<%= project.dist.js %>main.js'
                }
            }
        }
    });

    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');

    grunt.registerTask('default', [
        'concat',
        'uglify'
    ]);
};