# Avalanche Configuration
avalanche_imagine:
    filters:
        card:
            type:    thumbnail
            options: { size: [240, 300], mode: outbound }
        catalog:
            type:    thumbnail
            options: { size: [200, 250], mode: outbound }
        frame:
            type:    thumbnail
            options: { size: [190, 142], mode: outbound } # 12:9
        plugin:
            type:    thumbnail
            options: { size: [120, 120], mode: outbound }