parameters:
    anime_db.catalog.default_search: null
    anime_db.catalog.search_driver: anime_db.search.driver.sql_like
    anime_db.catalog.storage.scan_log: %kernel.logs_dir%/scan_storage.log
    anime_db.catalog.storage.scan_progress: %kernel.logs_dir%/scan_storage_progress.log