home:
    pattern:  /
    defaults: { _controller: AnimeDbCatalogBundle:Home:index }

home_search:
    pattern:  /search.html
    defaults: { _controller: AnimeDbCatalogBundle:Home:search }

home_autocomplete_name:
    pattern:  /autocomplete/name.json
    defaults: { _controller: AnimeDbCatalogBundle:Home:autocompleteName, _format: json }

home_settings:
    pattern:  /settings.html
    defaults: { _controller: AnimeDbCatalogBundle:Home:settings }


item_add_manually:
    pattern:  /add-manually.html
    defaults: { _controller: AnimeDbCatalogBundle:Item:addManually }

item_show:
    pattern:  /{id}-{name}/
    defaults: { _controller: AnimeDbCatalogBundle:Item:show }
    requirements:
        id:  \d+

item_change:
    pattern:  /{id}-{name}/change.html
    defaults: { _controller: AnimeDbCatalogBundle:Item:change }
    requirements:
        id:  \d+

item_delete:
    pattern:  /{id}-{name}/delete.html
    defaults: { _controller: AnimeDbCatalogBundle:Item:delete }
    requirements:
        id:  \d+

item_import:
    pattern:  /import/{plugin}.html
    defaults: { _controller: AnimeDbCatalogBundle:Item:import }

item_duplicate:
    pattern:  /duplicate.html
    defaults: { _controller: AnimeDbCatalogBundle:Item:duplicate }


storage_list:
    pattern:  /settings/storage.html
    defaults: { _controller: AnimeDbCatalogBundle:Storage:list }

storage_add:
    pattern:  /settings/storage/add.html
    defaults: { _controller: AnimeDbCatalogBundle:Storage:add }

storage_change:
    pattern:  /settings/storage/{id}/change.html
    defaults: { _controller: AnimeDbCatalogBundle:Storage:change }
    requirements:
        id:  \d+

storage_delete:
    pattern:  /settings/storage/{id}/delete.html
    defaults: { _controller: AnimeDbCatalogBundle:Storage:delete }
    requirements:
        id:  \d+


notice_get:
    pattern:  /notice/{id}/
    defaults: { _controller: AnimeDbCatalogBundle:Notice:get }
    requirements:
        id:  \d+

notice_list:
    pattern:  /notice/
    defaults: { _controller: AnimeDbCatalogBundle:Notice:list }


update:
    pattern:  /update/
    defaults: { _controller: AnimeDbCatalogBundle:Update:index }

update_exec:
    pattern:  /update/exec.html
    defaults: { _controller: AnimeDbCatalogBundle:Update:exec }
    methods:   [POST]


fill_filler:
    pattern:  /filler/{plugin}.html
    defaults: { _controller: AnimeDbCatalogBundle:Fill:filler }

fill_search:
    pattern:  /search/{plugin}.html
    defaults: { _controller: AnimeDbCatalogBundle:Fill:search }


refiller_refill:
    pattern:  /refiller/{plugin}/{field}/refill.html
    defaults: { _controller: AnimeDbCatalogBundle:Refill:refill }

refiller_search:
    pattern:  /refiller/{plugin}/{field}/search.html
    defaults: { _controller: AnimeDbCatalogBundle:Refill:search }

refiller_search_fill:
    pattern:  /refiller/{plugin}/{field}/from_search.html
    defaults: { _controller: AnimeDbCatalogBundle:Refill:fillFromSearch }


plugin_installed:
    pattern:  /plugin/installed.html
    defaults: { _controller: AnimeDbCatalogBundle:Plugin:installed }

plugin_store:
    pattern:  /plugin/store.html
    defaults: { _controller: AnimeDbCatalogBundle:Plugin:store }
