# Avalanche Configuration
avalanche_imagine:
    filters:
        catalog:
            type:    thumbnail
            options: { size: [200, 250], mode: outbound }
        frame:
            type:    thumbnail
            options: { size: [190, 142], mode: outbound } # 12:9
        plugin:
            type:    thumbnail
            options: { size: [120, 120], mode: outbound }

twig:
    globals:
        ga_account: 'UA-42991303-2'
        admin_email: 'support@anime-db.org'

assetic:
    bundles: [ AnimeDbCatalogBundle ]
    assets:
        stylesheets:
            inputs:
                - @AnimeDbCatalogBundle/Resources/public/css/*.css
        javascripts:
            inputs:
                - @AnimeDbCatalogBundle/Resources/public/js/*.js
