services:
    anime_db.plugin.filler:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Fill\Filler\Chain
    anime_db.plugin.search_fill:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Fill\Search\Chain
        arguments: [ %anime_db.catalog.default_search% ]
    anime_db.plugin.refiller:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Fill\Refiller\Chain
    anime_db.plugin.import:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Import\Chain
    anime_db.plugin.export:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Export\Chain
    anime_db.plugin.item:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Item\Chain
    anime_db.plugin.setting:
        class: AnimeDb\Bundle\CatalogBundle\Plugin\Setting\Chain