imports:
    - { resource: 'services/forms.yml' }
    - { resource: 'services/install.yml' }
    - { resource: 'services/listeners.yml' }
    - { resource: 'services/plugins.yml' }
    - { resource: 'services/search.yml' }
    - { resource: 'services/storage.yml' }

services:
    anime_db.catalog.twig.extension:
        class: AnimeDb\Bundle\CatalogBundle\Service\TwigExtension
        tags:
            - { name: twig.extension }

    anime_db.item.list_controls:
        class: AnimeDb\Bundle\CatalogBundle\Service\Item\ListControls
        arguments: [ '@anime_db.item.search' ]

    anime_db.menu.builder:
        class: AnimeDb\Bundle\CatalogBundle\Menu\Builder
        arguments:
            - '@knp_menu.factory'
            - '@request_stack'
            - '@translator'
            - '@anime_db.api.client'
            - '@anime_db.plugin.import'
            - '@anime_db.plugin.export'
            - '@anime_db.plugin.search_fill'
            - '@anime_db.plugin.filler'
            - '@anime_db.plugin.setting'
            - '@anime_db.plugin.item'
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createItemMenu, alias: item }
