services:
    # Twig extension
    anime_db.catalog.twig_extension:
        class: AnimeDb\Bundle\CatalogBundle\Service\TwigExtension
        tags:
            - { name: twig.extension }

    anime_db.item.search.driver.sql_like:
        class: AnimeDb\Bundle\CatalogBundle\Service\Item\Search\Driver\SqlLike
        arguments: [ @doctrine, anime_db.item.search.selector ]
        public: false
    anime_db.item.search.selector:
        class: AnimeDb\Bundle\CatalogBundle\Service\Item\Search\Selector
        arguments: [ @doctrine ]
        public: false
    anime_db.item.search:
        class: AnimeDb\Bundle\CatalogBundle\Service\Item\Search\Manager
        arguments: [ @anime_db.item.search.driver ]

    anime_db.item.list_controls:
        class: AnimeDb\Bundle\CatalogBundle\Service\Item\ListControls
        arguments: [ @anime_db.item.search ]
