services:
    # Twig extension
    anime_db.catalog.twig_extension:
        class: AnimeDb\Bundle\CatalogBundle\Service\TwigExtension
        tags:
            - { name: twig.extension }

    anime_db.api_client:
        class: AnimeDb\Bundle\CatalogBundle\Service\ApiClient
        arguments: [ %locale% ]

    anime_db.search.driver.sql_like:
        class: AnimeDb\Bundle\CatalogBundle\Service\Item\Search\Driver\SqlLike
        arguments: [ @doctrine ]
        public: false
    anime_db.search:
        class: AnimeDb\Bundle\CatalogBundle\Service\Item\Search\Manager
        arguments: [ @anime_db.search.driver ]

    anime_db.item_list_controls:
        class: AnimeDb\Bundle\CatalogBundle\Service\Item\ListControls
        arguments: [ @anime_db.search ]
